import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/Card';
import { Sparkles, AlertTriangle, Package, TrendingUp, Camera } from 'lucide-react';
import type { AIInsightItem } from '@/lib/mockData';

interface InsightFeedProps {
  insights: AIInsightItem[];
}

const getInsightIcon = (type: AIInsightItem['type']) => {
  switch (type) {
    case 'warning':
      return { icon: AlertTriangle, color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/20' };
    case 'inventory':
      return { icon: Package, color: 'text-rose-400', bg: 'bg-rose-500/10 border-rose-500/20' };
    case 'trend':
      return { icon: TrendingUp, color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/20' };
    case 'device':
      return { icon: Camera, color: 'text-sky-400', bg: 'bg-sky-500/10 border-sky-500/20' };
  }
};

const getSeverityBadge = (severity: AIInsightItem['severity']) => {
  switch (severity) {
    case 'high':
      return { label: 'High Priority', class: 'bg-rose-500/10 text-rose-400 border-rose-500/20' };
    case 'medium':
      return { label: 'Medium', class: 'bg-amber-500/10 text-amber-400 border-amber-500/20' };
    case 'info':
      return { label: 'Intelligence', class: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20' };
  }
};

export const InsightFeed: React.FC<InsightFeedProps> = ({ insights }) => {
  return (
    <Card className="bg-slate-900 border-slate-800">
      <CardHeader className="flex flex-row items-center justify-between pb-3">
        <div>
          <CardTitle className="text-white text-base flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-indigo-400" />
            <span>AI Automated Retail Insights</span>
          </CardTitle>
          <CardDescription>Live plain-language intelligence generated by edge vision algorithms</CardDescription>
        </div>
        <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
          Live Stream
        </span>
      </CardHeader>

      <CardContent>
        <div className="space-y-3 max-h-80 overflow-y-auto pr-1">
          <AnimatePresence initial={false}>
            {insights.map((item) => {
              const { icon: Icon, color, bg } = getInsightIcon(item.type);
              const severity = getSeverityBadge(item.severity);

              return (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, y: -12, scale: 0.98 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: 12, scale: 0.98 }}
                  transition={{ duration: 0.25, ease: 'easeOut' }}
                  className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/80 flex items-start gap-3.5 hover:border-slate-700 transition-all group"
                >
                  {/* Severity Icon Box */}
                  <div className={`p-2.5 rounded-xl border shrink-0 ${bg} ${color}`}>
                    <Icon className="w-4 h-4" />
                  </div>

                  {/* Insight Content */}
                  <div className="flex-1 min-w-0 space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <h4 className="text-xs font-bold text-white truncate">{item.title}</h4>
                      <div className="flex items-center gap-2 shrink-0">
                        <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${severity.class}`}>
                          {severity.label}
                        </span>
                        <span className="text-[11px] text-slate-500 font-mono">{item.timestamp}</span>
                      </div>
                    </div>
                    <p className="text-xs text-slate-300 leading-relaxed">{item.detail}</p>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      </CardContent>
    </Card>
  );
};
